// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fxx = require("./fxx.bs.js");
var Int64 = require("rescript/lib/js/int64.js");
var Printf = require("rescript/lib/js/printf.js");
var Caml_int64 = require("rescript/lib/js/caml_int64.js");
var Caml_format = require("rescript/lib/js/caml_format.js");

var to_hex_string = Printf.sprintf(/* Format */{
      _0: {
        TAG: /* Int64 */7,
        _0: /* Int_x */6,
        _1: /* No_padding */0,
        _2: /* No_precision */0,
        _3: /* End_of_format */0
      },
      _1: "%Lx"
    });

var include = Fxx.Make({
      mantissa: 52,
      zero: Int64.zero,
      min_int: Int64.min_int,
      max_int: Int64.max_int,
      pos_nan: [
        2146959360,
        0
      ],
      neg_nan: [
        -524288,
        0
      ],
      bare_nan: [
        2146435072,
        0
      ],
      bits_of_float: Caml_int64.bits_of_float,
      float_of_bits: Caml_int64.float_of_bits,
      of_string: Caml_format.caml_int64_of_string,
      to_string: Int64.to_string,
      to_hex_string: to_hex_string,
      lognot: Int64.lognot,
      logand: Caml_int64.and_,
      logor: Caml_int64.or_,
      logxor: Caml_int64.xor
    });

var pos_nan = include.pos_nan;

var neg_nan = include.neg_nan;

var is_inf = include.is_inf;

var is_nan = include.is_nan;

var of_float = include.of_float;

var to_float = include.to_float;

var of_string = include.of_string;

var to_string = include.to_string;

var to_hex_string$1 = include.to_hex_string;

var of_bits = include.of_bits;

var to_bits = include.to_bits;

var add = include.add;

var sub = include.sub;

var mul = include.mul;

var div = include.div;

var sqrt = include.sqrt;

var min = include.min;

var max = include.max;

var ceil = include.ceil;

var floor = include.floor;

var trunc = include.trunc;

var nearest = include.nearest;

var abs = include.abs;

var neg = include.neg;

var copysign = include.copysign;

var eq = include.eq;

var ne = include.ne;

var lt = include.lt;

var le = include.le;

var gt = include.gt;

var ge = include.ge;

var zero = include.zero;

exports.pos_nan = pos_nan;
exports.neg_nan = neg_nan;
exports.is_inf = is_inf;
exports.is_nan = is_nan;
exports.of_float = of_float;
exports.to_float = to_float;
exports.of_string = of_string;
exports.to_string = to_string;
exports.to_hex_string = to_hex_string$1;
exports.of_bits = of_bits;
exports.to_bits = to_bits;
exports.add = add;
exports.sub = sub;
exports.mul = mul;
exports.div = div;
exports.sqrt = sqrt;
exports.min = min;
exports.max = max;
exports.ceil = ceil;
exports.floor = floor;
exports.trunc = trunc;
exports.nearest = nearest;
exports.abs = abs;
exports.neg = neg;
exports.copysign = copysign;
exports.eq = eq;
exports.ne = ne;
exports.lt = lt;
exports.le = le;
exports.gt = gt;
exports.ge = ge;
exports.zero = zero;
/* include Not a pure module */
