// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function alloc(ft, inst, f) {
  return {
          TAG: /* AstFunc */0,
          _0: ft,
          _1: inst,
          _2: f
        };
}

function alloc_host(ft, f) {
  return {
          TAG: /* HostFunc */1,
          _0: ft,
          _1: f
        };
}

function type_of(param) {
  return param._0;
}

exports.alloc = alloc;
exports.alloc_host = alloc_host;
exports.type_of = type_of;
/* No side effect */
