// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Values from "../syntax/values.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

var Type = /* @__PURE__ */Caml_exceptions.create("Global.Type");

var NotMutable = /* @__PURE__ */Caml_exceptions.create("Global.NotMutable");

function alloc(ty, v) {
  if (Caml_obj.caml_notequal(Values.type_of_value(v), ty._0)) {
    throw {
          RE_EXN_ID: Type,
          Error: new Error()
        };
  }
  return {
          ty: ty,
          content: v
        };
}

function type_of(glob) {
  return glob.ty;
}

function load(glob) {
  return glob.content;
}

function store(glob, v) {
  var match = glob.ty;
  if (match._1 !== /* Mutable */1) {
    throw {
          RE_EXN_ID: NotMutable,
          Error: new Error()
        };
  }
  if (Caml_obj.caml_notequal(Values.type_of_value(v), match._0)) {
    throw {
          RE_EXN_ID: Type,
          Error: new Error()
        };
  }
  glob.content = v;
  
}

export {
  Type ,
  NotMutable ,
  alloc ,
  type_of ,
  load ,
  store ,
  
}
/* Values Not a pure module */
