// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Source from "./source.bs.js";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

function Make($star) {
  var $$Error = /* @__PURE__ */Caml_exceptions.create("Error.Make(*).Error");
  var warn = function (at, m) {
    console.error(Source.string_of_region(at) + (": warning: " + m));
    
  };
  var error = function (at, m) {
    throw {
          RE_EXN_ID: $$Error,
          _1: at,
          _2: m,
          Error: new Error()
        };
  };
  return {
          $$Error: $$Error,
          warn: warn,
          error: error
        };
}

export {
  Make ,
  
}
/* No side effect */
