// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Printf = require("rescript/lib/js/printf.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");

function $at$at(x, region) {
  return {
          at: region,
          it: x
        };
}

function at(region, x) {
  return {
          at: region,
          it: x
        };
}

var no_pos = {
  file: "",
  line: 0,
  column: 0
};

var no_region = {
  left: no_pos,
  right: no_pos
};

function string_of_pos(pos) {
  if (pos.line === -1) {
    return Curry._1(Printf.sprintf(/* Format */{
                    _0: {
                      TAG: /* String_literal */11,
                      _0: "0x",
                      _1: {
                        TAG: /* Int */4,
                        _0: /* Int_x */6,
                        _1: /* No_padding */0,
                        _2: /* No_precision */0,
                        _3: /* End_of_format */0
                      }
                    },
                    _1: "0x%x"
                  }), pos.column);
  } else {
    return String(pos.line) + ("." + String(pos.column + 1 | 0));
  }
}

function string_of_region(r) {
  return r.left.file + (":" + (string_of_pos(r.left) + (
              Caml_obj.caml_equal(r.right, r.left) ? "" : "-" + string_of_pos(r.right)
            )));
}

exports.no_pos = no_pos;
exports.no_region = no_region;
exports.string_of_pos = string_of_pos;
exports.string_of_region = string_of_region;
exports.$at$at = $at$at;
exports.at = at;
/* No side effect */
