// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "rescript/lib/es6/list.js";
import * as Sexpr from "../util/sexpr.bs.js";
import * as Arrange from "./arrange.bs.js";

function instr(oc, width, e) {
  return Sexpr.output(oc, width, Arrange.instr(e));
}

function func(oc, width, f) {
  return Sexpr.output(oc, width, Arrange.func(f));
}

function module_(oc, width, m) {
  return Sexpr.output(oc, width, Arrange.module_(m));
}

function script(oc, width, mode, s) {
  return List.iter((function (param) {
                return Sexpr.output(oc, width, param);
              }), Arrange.script(mode, s));
}

export {
  instr ,
  func ,
  module_ ,
  script ,
  
}
/* Arrange Not a pure module */
