// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("rescript/lib/js/list.js");
var Sexpr = require("../util/sexpr.bs.js");
var Arrange = require("./arrange.bs.js");

function instr(oc, width, e) {
  return Sexpr.output(oc, width, Arrange.instr(e));
}

function func(oc, width, f) {
  return Sexpr.output(oc, width, Arrange.func(f));
}

function module_(oc, width, m) {
  return Sexpr.output(oc, width, Arrange.module_(m));
}

function script(oc, width, mode, s) {
  return List.iter((function (param) {
                return Sexpr.output(oc, width, param);
              }), Arrange.script(mode, s));
}

exports.instr = instr;
exports.func = func;
exports.module_ = module_;
exports.script = script;
/* Arrange Not a pure module */
